name: Lambda Test

on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read # Required for actions/checkout

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    env:
      LAMBDA_TEST_PATH: "backend/test/lambda"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        architecture: "x64"
        cache: "pip"

    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f "${{ env.LAMBDA_TEST_PATH }}/requirements.txt" ]; then
          pip install -r "${{ env.LAMBDA_TEST_PATH }}/requirements.txt"
        fi

    - name: Run pytests
      run: |
        pytest "${{ env.LAMBDA_TEST_PATH }}/unit_tests/test_lambda.py" \
        --html="${{ env.LAMBDA_TEST_PATH }}/test-results.html" \
        --self-contained-html

    - name: Upload pytest results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: "${{ env.LAMBDA_TEST_PATH }}/test-results.html"
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
