name: Run Terraform

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read # Required for actions/checkout
  id-token: write # Required to request JSON Web Token for OIDC

jobs:
  run-terraform:
    runs-on: ubuntu-latest
    env:
        TF_VAR_aws_region: ${{ vars.AWS_REGION }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        TF_VAR_tags: ${{ vars.TAGS }}
        TF_VAR_aws_profile: null

    defaults:
      run:
        shell: bash
        working-directory: backend/src/terraform

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ !vars.LOCAL_DEVELOPMENT }}
      with:
        role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole"
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ vars.AWS_REGION }}

    - name: Configure AWS Credentials (SSO)
      uses: aws-actions/configure-aws-credentials@v4  
      if: ${{ vars.LOCAL_DEVELOPMENT }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: "0.123.7"
        extended: true

    - name: Update Hugo Theme
      run: git submodule update --remote --merge
      working-directory: ${{ github.workspace }}

    - name: Build Hugo
      run: hugo -D
      working-directory: frontend/src/hugo_site

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform changes
      run: terraform plan

    - name: Apply Terraform changes
      run: terraform apply -auto-approve