name: Run Terraform

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read # Required for actions/checkout
  id-token: write # Required to request JSON Web Token for OIDC

jobs:
  run-terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-west-1"

    defaults:
      run:
        shell: bash
        working-directory: backend/src/terraform

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      # with:
      #   role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole"
      #   role-session-name: GitHub_to_AWS_via_FederatedOIDC
      #   aws-region: "${{ env.AWS_REGION }}"
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}
      
    - name: Install Hugo
      run: |
        sudo apt-get update
        sudo apt-get install hugo -y

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Initialize Terraform
      run: | 
        pwd
        terraform init

    - name: Validate Terraform
      run: |
        pwd
        terraform validate

    - name: Plan Terraform changes
      run: |
        pwd
        terraform plan
      env:
        TF_VAR_aws_region: ${{ vars.AWS_REGION }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        TF_VAR_tags: ${{ vars.TAGS }}
        TF_VAR_aws_profile: null

    - name: Apply Terraform changes
      run: terraform apply -auto-approve
      env:
        TF_VAR_aws_region: ${{ vars.AWS_REGION }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        TF_VAR_tags: ${{ vars.TAGS }}
        TF_VAR_aws_profile: null