name: Test Lambda Python

on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON-VERSION: "3.13"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON-VERSION }}
        architecture: "x64"
        cache: "pip"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: pytest src/terraform/lambda/test/unit_tests/test_lambda.py --html=src/terraform/lambda/test/test-results-${{ env.PYTHON-VERSION }}.html --self-contained-html
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ env.PYTHON-VERSION }}
        path: src/terraform/lambda/test/test-results-${{ env.PYTHON-VERSION }}.html
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
